services:
  fintacharts.api:
    image: thesem1one/fintacharts:latest
    container_name: fintacharts
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__ApiDatabase=Host=fintachartsdb;Database=fintacharts;Username=postgres;Password=admin
      - FintaOptions__Token=eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJTUDJFWmlsdm8zS2g3aGEtSFRVU0I3bmZ6dERRN21tb3M3TXZndlI5UnZjIn0.eyJleHAiOjE3NTE2MjA2MjgsImlhdCI6MTc1MTYxODgyOCwianRpIjoiM2MxZTM4NzAtYWIxYi00NjYxLTllMDctZTMwZmMyZWVhMDI2IiwiaXNzIjoiaHR0cHM6Ly9wbGF0Zm9ybS5maW50YWNoYXJ0cy5jb20vaWRlbnRpdHkvcmVhbG1zL2ZpbnRhdGVjaCIsImF1ZCI6WyJiYXJzIiwibmV3cyIsImZpbnRhc2NyaXB0IiwiZWR1Y2F0aW9uIiwicHJvcC10cmFkaW5nIiwicGF5bWVudHMiLCJ0cmFkaW5nIiwid2ViLXNvY2tldHMtc3RyZWFtaW5nIiwidXNlci1kYXRhLXN0b3JlIiwiY29weS10cmFkZXIiLCJpbnN0cnVtZW50cyIsImFsZXJ0cy1jb25zb2xpZGF0b3IiLCJ1c2VyLXByb2ZpbGUiLCJhY2NvdW50Il0sInN1YiI6Ijk1ZTY2ZGJiLTQ3YTctNDhkOS05ZGZlLTRlYzZjZTQxY2I0MSIsInR5cCI6IkJlYXJlciIsImF6cCI6ImFwcC1jbGkiLCJzaWQiOiJjZDVhMjNjNS01Njk5LTQ2NDgtYTczYS0zYTcyMmZmMzRhNTQiLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsiZGVmYXVsdC1yb2xlcy1maW50YXRlY2giLCJ1c2VycyJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoicHJvZmlsZSIsInJvbGVzIjpbImRlZmF1bHQtcm9sZXMtZmludGF0ZWNoIiwidXNlcnMiXSwiZW1haWwiOiJyX3Rlc3RAZmludGF0ZWNoLmNvbSJ9.agZ-w-QomwPzBKAAdiM5Vv79r_LP-5nafiUZip5R2mkQJ21Ef1baDJ0Z0fokuCw5mi95hZ-T1-OCECiuGXnZJ7C0C95vaFRMeSXqAmvrtL-37o_LeXOnmh8HsXs1LQ2OMilvuLGkhwqZZ9ZBkXgan9mdIUkoJZ78f4vNe7YgAMb7LT_KRSrBXI05c475aA2X7Vdf7bq7klynk60ogppLjZRf1_Th-D4rtEE_QtdPe278IUtKIRV6-zu27bzW-EphjBR78mrrT0SgO0CCFj1t24u4uTOvtP-ln2QCAxeOZO_wcg-TrKGKrhtmis2FBzocK414UCGR7bcSLQSa_Hgygg
    depends_on:
          - fintachartsdb
    build:
      context: .
      dockerfile: Fintacharts.API/Dockerfile
    ports:
        - "8001:8080"

  fintachartsdb:
    image: postgres:11
    container_name: fintachartsdb
    restart: always
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=admin
        - POSTGRES_DB=fintacharts
    ports:
        - "9001:5432"